eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webstore

