spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webstore
      
zipkin:
    base-url: http://localhost:8083/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka
